app = 'sharpen-ts-documenter-broken-fog-1448'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[env]
  DB_PATH = '/litefs/analytics.db'
  PORT = '8081'

[mounts]
  source = "litefs"
  destination = "/data"

[processes]
  app = "streamlit run --server.port 8081 document_ts_file.py"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]